In [6]:
import pandas as pd

In [7]:
df = pd.read_parquet("queries.parquet")

In [8]:
df

,model_id,dag_id,query_id,combination_index,query_index_in_combination,num_query_nodes_param,num_evidence_nodes_param,distance_bucket_param,query_string,query_vars,...,evidence,exact_probability,query_metadata,num_query_nodes_actual,num_evidence_nodes_actual,min_target_evidence_distance,distance_bucket_actual,evidence_distances,combo_seed,query_created_at
0,model_0001,dag_0001,query_000001,0,0,1,1,"[1, 1]",P(V4=s1 | V5=s1),"[""V4""]",...,"{""V5"": ""s1""}",0.869188,"{""num_query_nodes"": 1, ""num_evidence_nodes"": 1...",1,1,1,"[1, 1]","[{""query_var"": ""V4"", ""evidence_var"": ""V5"", ""di...",1000,2025-09-20T23:38:50.580725
1,model_0001,dag_0001,query_000002,0,1,1,1,"[1, 1]",P(V4=s1 | V7=s1),"[""V4""]",...,"{""V7"": ""s1""}",0.982376,"{""num_query_nodes"": 1, ""num_evidence_nodes"": 1...",1,1,1,"[1, 1]","[{""query_var"": ""V4"", ""evidence_var"": ""V7"", ""di...",1000,2025-09-20T23:38:50.580725
2,model_0001,dag_0001,query_000003,1,0,1,1,"[2, 3]",P(V5=s3 | V7=s0),"[""V5""]",...,"{""V7"": ""s0""}",0.649825,"{""num_query_nodes"": 1, ""num_evidence_nodes"": 1...",1,1,2,"[2, 3]","[{""query_var"": ""V5"", ""evidence_var"": ""V7"", ""di...",1100,2025-09-20T23:38:50.580725
3,model_0001,dag_0001,query_000004,1,1,1,1,"[2, 3]",P(V7=s0 | V9=s0),"[""V7""]",...,"{""V9"": ""s0""}",0.808758,"{""num_query_nodes"": 1, ""num_evidence_nodes"": 1...",1,1,2,"[2, 3]","[{""query_var"": ""V7"", ""evidence_var"": ""V9"", ""di...",1100,2025-09-20T23:38:50.580725
4,model_0001,dag_0001,query_000005,2,0,1,1,"[4, 9]",P(V9=s0 | V5=s2),"[""V9""]",...,"{""V5"": ""s2""}",0.241195,"{""num_query_nodes"": 1, ""num_evidence_nodes"": 1...",1,1,4,"[4, 9]","[{""query_var"": ""V9"", ""evidence_var"": ""V5"", ""di...",1200,2025-09-20T23:38:50.580725
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40315,model_1680,dag_0210,query_040316,9,1,2,2,"[1, 1]","P(J_7blg6w=s1, H_p78r4l=s0 | I_joyr5y=s0, B_vv...","[""J_7blg6w"", ""H_p78r4l""]",...,"{""I_joyr5y"": ""s0"", ""B_vvyidm"": ""s0""}",0.073513,"{""num_query_nodes"": 2, ""num_evidence_nodes"": 2...",2,2,1,"[1, 1]","[{""query_var"": ""J_7blg6w"", ""evidence_var"": ""I_...",1680900,2025-09-20T23:38:50.580725
40316,model_1680,dag_0210,query_040317,10,0,2,2,"[2, 3]","P(U_9jr4il=s1, P_dnnfdt=s0 | F_lscv2k=s0, D_wj...","[""U_9jr4il"", ""P_dnnfdt""]",...,"{""F_lscv2k"": ""s0"", ""D_wjx03p"": ""s1""}",0.244163,"{""num_query_nodes"": 2, ""num_evidence_nodes"": 2...",2,2,2,"[2, 3]","[{""query_var"": ""U_9jr4il"", ""evidence_var"": ""F_...",1681000,2025-09-20T23:38:50.580725
40317,model_1680,dag_0210,query_040318,10,1,2,2,"[2, 3]","P(S_qqipkr=s0, J_khdh6i=s0 | G_6yjvok=s1, Q_mr...","[""S_qqipkr"", ""J_khdh6i""]",...,"{""G_6yjvok"": ""s1"", ""Q_mrnc1u"": ""s1""}",0.179000,"{""num_query_nodes"": 2, ""num_evidence_nodes"": 2...",2,2,2,"[2, 3]","[{""query_var"": ""S_qqipkr"", ""evidence_var"": ""G_...",1681000,2025-09-20T23:38:50.580725
40318,model_1680,dag_0210,query_040319,11,0,2,2,"[4, 9]","P(H_p78r4l=s3, P_sgqkgv=s1 | I_p0s6a1=s3, N_6p...","[""H_p78r4l"", ""P_sgqkgv""]",...,"{""I_p0s6a1"": ""s3"", ""N_6pmm5a"": ""s1""}",0.010929,"{""num_query_nodes"": 2, ""num_evidence_nodes"": 2...",2,2,3,"[4, 9]","[{""query_var"": ""H_p78r4l"", ""evidence_var"": ""I_...",1681100,2025-09-20T23:38:50.580725
40319,model_1680,dag_0210,query_040320,11,1,2,2,"[4, 9]","P(J_7blg6w=s1, V_vm7445=s3 | A_q570s2=s0, K_w1...","[""J_7blg6w"", ""V_vm7445""]",...,"{""A_q570s2"": ""s0"", ""K_w1o785"": ""s1""}",0.094303,"{""num_query_nodes"": 2, ""num_evidence_nodes"": 2...",2,2,3,"[4, 9]","[{""query_var"": ""J_7blg6w"", ""evidence_var"": ""A_...",1681100,2025-09-20T23:38:50.580725